### ISSUE TITLE
'null' as default is not possible for optional parameter. 

### ISSUE THREAD

**Issue by Gemineye** [Becklyn/RouteTreeBundle#4]
The generated navigation link is '/route/1' and not '/route'

``` yml
some_route:
    path: /route/{parameter}
    defaults:
        _controller: MyController
        parameter: ~
    requirements:
        parameter: \d+
    options:
        page_tree:
            parent: home
            parameters: {'parameter': ~}
            title: Title
```
